[
  {
    id: 1,
    name: "Bulbasaur",
    type: ["Grass", "Poison"],
    total_base_stats: 318,
  },
  { id: 2, name: "Ivysaur", type: ["Grass", "Poison"], total_base_stats: 405 },
  { id: 3, name: "Venusaur", type: ["Grass", "Poison"], total_base_stats: 525 },
  { id: 4, name: "Charmander", type: ["Fire"], total_base_stats: 309 },
  { id: 5, name: "Charmeleon", type: ["Fire"], total_base_stats: 405 },
  { id: 6, name: "Charizard", type: ["Fire", "Flying"], total_base_stats: 534 },
  { id: 7, name: "Squirtle", type: ["Water"], total_base_stats: 314 },
  { id: 8, name: "Wartortle", type: ["Water"], total_base_stats: 405 },
  { id: 9, name: "Blastoise", type: ["Water"], total_base_stats: 530 },
  { id: 10, name: "Caterpie", type: ["Bug"], total_base_stats: 195 },
  { id: 11, name: "Metapod", type: ["Bug"], total_base_stats: 205 },
  {
    id: 12,
    name: "Butterfree",
    type: ["Bug", "Flying"],
    total_base_stats: 395,
  },
  { id: 13, name: "Weedle", type: ["Bug", "Poison"], total_base_stats: 195 },
  { id: 14, name: "Kakuna", type: ["Bug", "Poison"], total_base_stats: 205 },
  { id: 15, name: "Beedrill", type: ["Bug", "Poison"], total_base_stats: 395 },
  { id: 16, name: "Pidgey", type: ["Normal", "Flying"], total_base_stats: 251 },
  {
    id: 17,
    name: "Pidgeotto",
    type: ["Normal", "Flying"],
    total_base_stats: 349,
  },
  {
    id: 18,
    name: "Pidgeot",
    type: ["Normal", "Flying"],
    total_base_stats: 479,
  },
  { id: 19, name: "Rattata", type: ["Normal"], total_base_stats: 253 },
  { id: 20, name: "Raticate", type: ["Normal"], total_base_stats: 413 },
  {
    id: 21,
    name: "Spearow",
    type: ["Normal", "Flying"],
    total_base_stats: 251,
  },
  { id: 22, name: "Fearow", type: ["Normal", "Flying"], total_base_stats: 349 },
  { id: 23, name: "Ekans", type: ["Poison"], total_base_stats: 288 },
  { id: 24, name: "Arbok", type: ["Poison"], total_base_stats: 438 },
  { id: 25, name: "Pikachu", type: ["Electric"], total_base_stats: 320 },
  { id: 26, name: "Raichu", type: ["Electric"], total_base_stats: 485 },
  { id: 27, name: "Sandshrew", type: ["Ground"], total_base_stats: 300 },
  { id: 28, name: "Sandslash", type: ["Ground"], total_base_stats: 450 },
  { id: 29, name: "Nidoran♀", type: ["Poison"], total_base_stats: 273 },
  { id: 30, name: "Nidorina", type: ["Poison"], total_base_stats: 365 },
  {
    id: 31,
    name: "Nidoqueen",
    type: ["Poison", "Ground"],
    total_base_stats: 505,
  },
  { id: 32, name: "Nidoran♂", type: ["Poison"], total_base_stats: 273 },
  { id: 33, name: "Nidorino", type: ["Poison"], total_base_stats: 365 },
  {
    id: 34,
    name: "Nidoking",
    type: ["Poison", "Ground"],
    total_base_stats: 505,
  },
  { id: 35, name: "Clefairy", type: ["Fairy"], total_base_stats: 323 },
  { id: 36, name: "Clefable", type: ["Fairy"], total_base_stats: 483 },
  { id: 37, name: "Vulpix", type: ["Fire"], total_base_stats: 299 },
  { id: 38, name: "Ninetales", type: ["Fire"], total_base_stats: 505 },
  {
    id: 39,
    name: "Jigglypuff",
    type: ["Normal", "Fairy"],
    total_base_stats: 435,
  },
  {
    id: 40,
    name: "Wigglytuff",
    type: ["Normal", "Fairy"],
    total_base_stats: 560,
  },
  { id: 41, name: "Zubat", type: ["Poison", "Flying"], total_base_stats: 245 },
  { id: 42, name: "Golbat", type: ["Poison", "Flying"], total_base_stats: 435 },
  { id: 43, name: "Oddish", type: ["Grass", "Poison"], total_base_stats: 320 },
  { id: 44, name: "Gloom", type: ["Grass", "Poison"], total_base_stats: 395 },
  {
    id: 45,
    name: "Vileplume",
    type: ["Grass", "Poison"],
    total_base_stats: 490,
  },
  { id: 46, name: "Paras", type: ["Bug", "Grass"], total_base_stats: 285 },
  { id: 47, name: "Parasect", type: ["Bug", "Grass"], total_base_stats: 405 },
  { id: 48, name: "Venonat", type: ["Bug", "Poison"], total_base_stats: 305 },
  { id: 49, name: "Venomoth", type: ["Bug", "Poison"], total_base_stats: 450 },
  { id: 50, name: "Diglett", type: ["Ground"], total_base_stats: 265 },
  { id: 51, name: "Dugtrio", type: ["Ground"], total_base_stats: 425 },
  { id: 52, name: "Meowth", type: ["Normal"], total_base_stats: 290 },
  { id: 53, name: "Persian", type: ["Normal"], total_base_stats: 440 },
  { id: 54, name: "Psyduck", type: ["Water"], total_base_stats: 320 },
  { id: 55, name: "Golduck", type: ["Water"], total_base_stats: 500 },
  { id: 56, name: "Mankey", type: ["Fighting"], total_base_stats: 305 },
  { id: 57, name: "Primeape", type: ["Fighting"], total_base_stats: 455 },
  { id: 58, name: "Growlithe", type: ["Fire"], total_base_stats: 350 },
  { id: 59, name: "Arcanine", type: ["Fire"], total_base_stats: 555 },
  { id: 60, name: "Poliwag", type: ["Water"], total_base_stats: 300 },
  { id: 61, name: "Poliwhirl", type: ["Water"], total_base_stats: 385 },
  { id: 62, name: "Politoed", type: ["Water"], total_base_stats: 500 },
  { id: 63, name: "Abra", type: ["Psychic"], total_base_stats: 310 },
  { id: 64, name: "Kadabra", type: ["Psychic"], total_base_stats: 400 },
  { id: 65, name: "Alakazam", type: ["Psychic"], total_base_stats: 500 },
  { id: 66, name: "Machop", type: ["Fighting"], total_base_stats: 305 },
  { id: 67, name: "Machoke", type: ["Fighting"], total_base_stats: 405 },
  { id: 68, name: "Machamp", type: ["Fighting"], total_base_stats: 505 },
  {
    id: 69,
    name: "Bellsprout",
    type: ["Grass", "Poison"],
    total_base_stats: 290,
  },
  {
    id: 70,
    name: "Weepinbell",
    type: ["Grass", "Poison"],
    total_base_stats: 390,
  },
  {
    id: 71,
    name: "Victreebel",
    type: ["Grass", "Poison"],
    total_base_stats: 490,
  },
  {
    id: 71,
    name: "Victreebel",
    type: ["Grass", "Poison"],
    total_base_stats: 490,
  },
  {
    id: 72,
    name: "Tentacool",
    type: ["Water", "Poison"],
    total_base_stats: 335,
  },
  {
    id: 73,
    name: "Tentacruel",
    type: ["Water", "Poison"],
    total_base_stats: 515,
  },
  { id: 74, name: "Geodude", type: ["Rock", "Ground"], total_base_stats: 300 },
  { id: 75, name: "Graveler", type: ["Rock", "Ground"], total_base_stats: 390 },
  { id: 76, name: "Golem", type: ["Rock", "Ground"], total_base_stats: 495 },
  { id: 77, name: "Ponyta", type: ["Fire"], total_base_stats: 410 },
  { id: 78, name: "Rapidash", type: ["Fire"], total_base_stats: 500 },
  {
    id: 79,
    name: "Slowpoke",
    type: ["Water", "Psychic"],
    total_base_stats: 315,
  },
  {
    id: 80,
    name: "Slowbro",
    type: ["Water", "Psychic"],
    total_base_stats: 490,
  },
  {
    id: 81,
    name: "Magnemite",
    type: ["Electric", "Steel"],
    total_base_stats: 325,
  },
  {
    id: 82,
    name: "Magneton",
    type: ["Electric", "Steel"],
    total_base_stats: 465,
  },
  {
    id: 83,
    name: "Farfetch'd",
    type: ["Normal", "Flying"],
    total_base_stats: 352,
  },
  { id: 84, name: "Doduo", type: ["Normal", "Flying"], total_base_stats: 310 },
  { id: 85, name: "Dodrio", type: ["Normal", "Flying"], total_base_stats: 460 },
  { id: 86, name: "Seel", type: ["Water"], total_base_stats: 325 },
  { id: 87, name: "Dewgong", type: ["Water", "Ice"], total_base_stats: 475 },
  { id: 88, name: "Grimer", type: ["Poison"], total_base_stats: 325 },
  { id: 89, name: "Muk", type: ["Poison"], total_base_stats: 500 },
  { id: 90, name: "Shellder", type: ["Water"], total_base_stats: 305 },
  { id: 91, name: "Cloyster", type: ["Water", "Ice"], total_base_stats: 525 },
  { id: 92, name: "Gastly", type: ["Ghost", "Poison"], total_base_stats: 310 },
  { id: 93, name: "Haunter", type: ["Ghost", "Poison"], total_base_stats: 405 },
  { id: 94, name: "Gengar", type: ["Ghost", "Poison"], total_base_stats: 500 },
  { id: 95, name: "Onix", type: ["Rock", "Ground"], total_base_stats: 385 },
  { id: 96, name: "Drowzee", type: ["Psychic"], total_base_stats: 328 },
  { id: 97, name: "Hypno", type: ["Psychic"], total_base_stats: 483 },
  { id: 98, name: "Krabby", type: ["Water"], total_base_stats: 325 },
  { id: 99, name: "Kingler", type: ["Water"], total_base_stats: 475 },
  { id: 100, name: "Voltorb", type: ["Electric"], total_base_stats: 330 },
  { id: 101, name: "Electrode", type: ["Electric"], total_base_stats: 480 },
  {
    id: 102,
    name: "Exeggcute",
    type: ["Grass", "Psychic"],
    total_base_stats: 325,
  },
  {
    id: 103,
    name: "Exeggutor",
    type: ["Grass", "Psychic"],
    total_base_stats: 520,
  },
  { id: 104, name: "Cubone", type: ["Ground"], total_base_stats: 320 },
  { id: 105, name: "Marowak", type: ["Ground"], total_base_stats: 425 },
  { id: 106, name: "Hitmonlee", type: ["Fighting"], total_base_stats: 455 },
  { id: 107, name: "Hitmonchan", type: ["Fighting"], total_base_stats: 455 },
  { id: 108, name: "Lickitung", type: ["Normal"], total_base_stats: 385 },
  { id: 109, name: "Koffing", type: ["Poison"], total_base_stats: 340 },
  { id: 110, name: "Weezing", type: ["Poison"], total_base_stats: 490 },
  { id: 111, name: "Rhyhorn", type: ["Ground", "Rock"], total_base_stats: 345 },
  { id: 112, name: "Rhydon", type: ["Ground", "Rock"], total_base_stats: 485 },
  { id: 113, name: "Chansey", type: ["Normal"], total_base_stats: 450 },
  { id: 114, name: "Tangela", type: ["Grass"], total_base_stats: 435 },
  { id: 115, name: "Kangaskhan", type: ["Normal"], total_base_stats: 490 },
  { id: 116, name: "Horsea", type: ["Water"], total_base_stats: 295 },
  { id: 117, name: "Seadra", type: ["Water"], total_base_stats: 440 },
  { id: 118, name: "Goldeen", type: ["Water"], total_base_stats: 320 },
  { id: 119, name: "Seaking", type: ["Water"], total_base_stats: 450 },
  { id: 120, name: "Staryu", type: ["Water"], total_base_stats: 340 },
  {
    id: 121,
    name: "Starmie",
    type: ["Water", "Psychic"],
    total_base_stats: 520,
  },
  {
    id: 122,
    name: "Mr. Mime",
    type: ["Psychic", "Fairy"],
    total_base_stats: 460,
  },
  { id: 123, name: "Scyther", type: ["Bug", "Flying"], total_base_stats: 500 },
  { id: 124, name: "Jynx", type: ["Ice", "Psychic"], total_base_stats: 455 },
  { id: 125, name: "Electabuzz", type: ["Electric"], total_base_stats: 490 },
  { id: 126, name: "Magmar", type: ["Fire"], total_base_stats: 495 },
  { id: 127, name: "Pinsir", type: ["Bug"], total_base_stats: 500 },
  { id: 128, name: "Tauros", type: ["Normal"], total_base_stats: 490 },
  { id: 129, name: "Magikarp", type: ["Water"], total_base_stats: 200 },
  {
    id: 130,
    name: "Gyarados",
    type: ["Water", "Flying"],
    total_base_stats: 540,
  },
  { id: 131, name: "Lapras", type: ["Water", "Ice"], total_base_stats: 535 },
  { id: 132, name: "Ditto", type: ["Normal"], total_base_stats: 288 },
  { id: 133, name: "Eevee", type: ["Normal"], total_base_stats: 325 },
  { id: 134, name: "Vaporeon", type: ["Water"], total_base_stats: 525 },
  { id: 135, name: "Jolteon", type: ["Electric"], total_base_stats: 525 },
  { id: 136, name: "Flareon", type: ["Fire"], total_base_stats: 525 },
  { id: 137, name: "Porygon", type: ["Normal"], total_base_stats: 395 },
  { id: 138, name: "Omanyte", type: ["Rock", "Water"], total_base_stats: 355 },
  { id: 139, name: "Omastar", type: ["Rock", "Water"], total_base_stats: 495 },
  { id: 140, name: "Kabuto", type: ["Rock", "Water"], total_base_stats: 355 },
  { id: 141, name: "Kabutops", type: ["Rock", "Water"], total_base_stats: 495 },
  {
    id: 142,
    name: "Aerodactyl",
    type: ["Rock", "Flying"],
    total_base_stats: 515,
  },
  { id: 143, name: "Snorlax", type: ["Normal"], total_base_stats: 540 },
  { id: 144, name: "Articuno", type: ["Ice", "Flying"], total_base_stats: 580 },
  {
    id: 145,
    name: "Zapdos",
    type: ["Electric", "Flying"],
    total_base_stats: 580,
  },
  { id: 146, name: "Moltres", type: ["Fire", "Flying"], total_base_stats: 580 },
  { id: 147, name: "Dratini", type: ["Dragon"], total_base_stats: 300 },
  { id: 148, name: "Dragonair", type: ["Dragon"], total_base_stats: 420 },
  {
    id: 149,
    name: "Dragonite",
    type: ["Dragon", "Flying"],
    total_base_stats: 600,
  },
  { id: 150, name: "Mewtwo", type: ["Psychic"], total_base_stats: 680 },
  { id: 151, name: "Mew", type: ["Psychic"], total_base_stats: 600 },
];
